### ISSUE TITLE
General Recommendations

### ISSUE THREAD

**Issue by CanadaHonk** [Controlfreak707/GM-Module-Template#1]
- Don't include unsupported types in settings as it seems misleading as if they can actually be used
 - Move settings item adding to `onImport`, `onLoadingFinished` is being deprecated soon-ish
 - Remove default in switch for `setSetting` since a wrong setting name should never be called as it is developer-side, not user input

**Comment by Controlfreak707** [comment]
For your third point, what if the developer messes up? The template is made to be used by developers that don't want to write their own module from scratch, developers that'll probably make a mistake here and there. It should be the developer's decision to remove the default code in the switch statement when they decide they no longer need it.

**Comment by CanadaHonk** [comment]
I guess, yeah.

**Comment by Controlfreak707** [comment]
Resolved with commit bd93a37
